### PR TITLE
gh-457: Align Mauro Data Specification functionality with latest sde-…

### LINKED ISSUE #457: Update explorer for request Data Specifications Ids
Must be tested alongside:
maurodatamapper/sde-core#231
maurodatamapper/sde-resources#138

maurodatamapper/sde-core#231 has made changes to how Mauro Data Specifications are handled in the sde-core. The mdm-explorer needs to be updated to align with these changes.

Once this and maurodatamapper/sde-resources#138 are complete: 
1. A researcher should be able to Submit Data Specifications as Data Requests in exactly the same way as they could before these changes were made.
2. A researcher won't be able to submit a New Project Request because they will get an error telling them that a Data Specification is required. This functionality will be added in other tasks (see epic)

### PR DESCRIPTION
**Pull request by NigelPalmer**
…core changes

closes #457

### CODE REVIEW

**Comment by NigelPalmer** [comment]
Note: These tests will keep failing until the sde-resources changes are pushed to develop

**Comment by jamesrwelch** [comment]
@NigelPalmer You can update the GitHub actions file to test against a different branch of sde-resources, as long as you change it back before merging into develop 👍

**Review by greg-at-occ — DISMISSED** [review]
Looks good to me

**Comment by NigelPalmer** [comment]
This has been updated again to align with the latest sde-core changes.

**Review by greg-at-occ — CHANGES_REQUESTED** [review]
Changes will be needed here if you agree that the type name should change. But otherwise just send it back and I will approve

**Review by greg-at-occ — DISMISSED** [review]
That was easy!

**Review by greg-at-occ — APPROVED** [review]

**Pull request merged**
